FROM n8nio/n8n:latest

# Set environment variables for n8n
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=${DB_HOST}
ENV DB_POSTGRESDB_PORT=${DB_PORT}
ENV DB_POSTGRESDB_DATABASE=${DB_DATABASE}
ENV DB_POSTGRESDB_USER=${DB_USER}
ENV DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=${N8N_USERNAME}
ENV N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
ENV WEBHOOK_URL=${RENDER_EXTERNAL_URL}
ENV N8N_EDITOR_BASE_URL=${RENDER_EXTERNAL_URL}
ENV N8N_DEFAULT_BINARY_DATA_MODE=filesystem
ENV N8N_LOG_LEVEL=info
ENV N8N_LOG_OUTPUT=console
ENV N8N_DIAGNOSTICS_ENABLED=false
