services:
  - type: web
    name: n8n
    env: docker
    repo: VictorJK-jpg/n8n-render-manual # CORRECTED: Removed https://
    buildCommand: ""
    healthCheckPath: /healthz
    plan: free
    envVars:
      - key: N8N_USERNAME
        generateValue: true
      - key: N8N_PASSWORD
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      # Optional: Add your Zoho Mail SMTP credentials here for security
      # Uncomment and fill these if you want to store them as environment variables
      # - key: N8N_EMAIL_SMTP_HOST
      #   value: smtp.zoho.com
      # - key: N8N_EMAIL_SMTP_PORT
      #   value: 587
      # - key: N8N_EMAIL_SMTP_USER
      #   value: your@zoho.com
      # - key: N8N_EMAIL_SMTP_PASS
      #   value: your_app_password # Use an app password if 2FA is on
  - type: pserv
    name: n8n-db
    plan: free
    # IMPORTANT: No other properties like databaseName, ipAllowList, runtime, or startCommand
    # should be here for a pserv type in a blueprint.
