services:
  - type: web
    name: n8n # Name of your n8n web service
    plan: free # Use the free web service plan
    runtime: image # THIS IS THE KEY CHANGE: Tells Render to use a pre-built Docker image
    image:
      url: docker.io/n8nio/n8n:latest # Specifies the official n8n Docker image
    # No buildCommand, no startCommand, no repo needed when using runtime: image
    healthCheckPath: /healthz # Good practice for health checks
    envVars:
      - key: N8N_USERNAME
        generateValue: true # Render will generate a strong username
      - key: N8N_PASSWORD
        generateValue: true # Render will generate a strong password
      - key: DB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      # Optional: Add your Zoho Mail SMTP credentials here for security
      # Uncomment and fill these if you want to store them as environment variables
      # - key: N8N_EMAIL_SMTP_HOST
      #   value: smtp.zoho.com
      # - key: N8N_EMAIL_SMTP_PORT
      #   value: 587
      # - key: N8N_EMAIL_SMTP_USER
      #   value: your@zoho.com
      # - key: N8N_EMAIL_SMTP_PASS
      #   value: your_app_password # Use an app password if 2FA is on
  - type: pserv
    name: n8n-db # Name of your PostgreSQL database service
    plan: free # Use the free PostgreSQL plan
    # As per documentation, no other properties like databaseName, ipAllowList, runtime, or startCommand
    # are needed here for a pserv type in a blueprint. Render handles these implicitly.
