services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/VictorJK-jpg/n8n-render-manual.git
    buildCommand: ""
    startCommand: "n8n"
    healthCheckPath: /healthz
    plan: free
    envVars:
      - key: N8N_USERNAME
        generateValue: true
      - key: N8N_PASSWORD
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
  - type: pserv
    name: n8n-db
    plan: free
    databaseName: n8n
    ipAllowList: []
